#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kubernetes
Version  : 1.15.3
Release  : 81
URL      : https://github.com/kubernetes/kubernetes/archive/v1.15.3.tar.gz
Source0  : https://github.com/kubernetes/kubernetes/archive/v1.15.3.tar.gz
Source1  : kube-apiserver.service
Source2  : kube-controller-manager.service
Source3  : kube-proxy.service
Source4  : kube-scheduler.service
Source5  : kubelet-motd.service
Source6  : kubelet.service
Summary  : Container Cluster Manager - CNI plugins
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-4.0 CC-BY-SA-4.0 CC0-1.0 GPL-2.0 ISC LGPL-3.0 MIT MPL-2.0 MPL-2.0-no-copyleft-exception NCSA
Requires: kubernetes-bin = %{version}-%{release}
Requires: kubernetes-license = %{version}-%{release}
Requires: kubernetes-services = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : curl
BuildRequires : go
BuildRequires : rsync
Patch1: 0001-Add-kubelet-version-checker-script.patch
Patch2: 0002-add-systemd-link-file-which-explicitly-sets-macaddr-policy.patch

%description
Binaries required to provision container networking.

%package bin
Summary: bin components for the kubernetes package.
Group: Binaries
Requires: kubernetes-license = %{version}-%{release}
Requires: kubernetes-services = %{version}-%{release}

%description bin
bin components for the kubernetes package.


%package extras
Summary: extras components for the kubernetes package.
Group: Default

%description extras
extras components for the kubernetes package.


%package license
Summary: license components for the kubernetes package.
Group: Default

%description license
license components for the kubernetes package.


%package services
Summary: services components for the kubernetes package.
Group: Systemd services

%description services
services components for the kubernetes package.


%prep
%setup -q -n kubernetes-1.15.3
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566321497
export GCC_IGNORE_WERROR=1
export GOPROXY=file:///usr/share/goproxy
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
make all WHAT="cmd/kubeadm cmd/kubectl cmd/kubelet cmd/kube-proxy cmd/kube-controller-manager cmd/kube-apiserver cmd/kube-scheduler"


%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cat >excludetests <<EOF
cmd/kubeadm/app/cmd
cmd/kubeadm/app/cmd/phases
cmd/kubeadm/app/cmd/phases/certs
cmd/kubeadm/app/phases/certs
cmd/kubeadm/app/phases/upgrade
cmd/kubeadm/app/util
cmd/kubeadm/test/cmd
pkg/kubelet/cm/devicemanager
pkg/kubelet/kuberuntime
pkg/kubelet/network/dns
pkg/kubelet/winstats
pkg/kubelet/oom
EOF
make test WHAT="`find ./cmd/kubeadm ./pkg/kubectl ./pkg/kubelet/ -name '*_test.go' -exec dirname '{}' \;|sort -u|grep -v -f excludetests|tr '\n' ' '`" || :

%install
export SOURCE_DATE_EPOCH=1566321497
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kubernetes
cp Godeps/LICENSES %{buildroot}/usr/share/package-licenses/kubernetes/Godeps_LICENSES
cp LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/LICENSE
cp logo/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/logo_LICENSE
cp staging/src/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_api_LICENSE
cp staging/src/k8s.io/apiextensions-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apiextensions-apiserver_LICENSE
cp staging/src/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apimachinery_LICENSE
cp staging/src/k8s.io/apiserver/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apiserver_LICENSE
cp staging/src/k8s.io/cli-runtime/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cli-runtime_LICENSE
cp staging/src/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_client-go_LICENSE
cp staging/src/k8s.io/cloud-provider/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cloud-provider_LICENSE
cp staging/src/k8s.io/cluster-bootstrap/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cluster-bootstrap_LICENSE
cp staging/src/k8s.io/code-generator/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_code-generator_LICENSE
cp staging/src/k8s.io/component-base/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_component-base_LICENSE
cp staging/src/k8s.io/cri-api/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cri-api_LICENSE
cp staging/src/k8s.io/csi-translation-lib/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_csi-translation-lib_LICENSE
cp staging/src/k8s.io/kube-aggregator/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-aggregator_LICENSE
cp staging/src/k8s.io/kube-controller-manager/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-controller-manager_LICENSE
cp staging/src/k8s.io/kube-proxy/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-proxy_LICENSE
cp staging/src/k8s.io/kube-scheduler/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-scheduler_LICENSE
cp staging/src/k8s.io/kubectl/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kubectl_LICENSE
cp staging/src/k8s.io/kubelet/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kubelet_LICENSE
cp staging/src/k8s.io/legacy-cloud-providers/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_legacy-cloud-providers_LICENSE
cp staging/src/k8s.io/metrics/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_metrics_LICENSE
cp staging/src/k8s.io/node-api/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_node-api_LICENSE
cp staging/src/k8s.io/sample-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-apiserver_LICENSE
cp staging/src/k8s.io/sample-cli-plugin/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-cli-plugin_LICENSE
cp staging/src/k8s.io/sample-controller/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-controller_LICENSE
cp third_party/forked/golang/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_forked_golang_LICENSE
cp third_party/forked/gonum/graph/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_forked_gonum_graph_LICENSE
cp third_party/forked/shell2junit/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_forked_shell2junit_LICENSE
cp third_party/go-srcimporter/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_go-srcimporter_LICENSE
cp third_party/intemp/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_intemp_LICENSE
cp third_party/multiarch/qemu-user-static/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/third_party_multiarch_qemu-user-static_LICENSE
cp vendor/bitbucket.org/bertimus9/systemstat/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_bitbucket.org_bertimus9_systemstat_LICENSE
cp vendor/cloud.google.com/go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_cloud.google.com_go_LICENSE
cp vendor/github.com/Azure/azure-sdk-for-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_azure-sdk-for-go_LICENSE
cp vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_go-ansiterm_LICENSE
cp vendor/github.com/Azure/go-autorest/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_go-autorest_LICENSE
cp vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_GoogleCloudPlatform_k8s-cloud-provider_LICENSE
cp vendor/github.com/JeffAshton/win_pdh/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_JeffAshton_win_pdh_LICENSE
cp vendor/github.com/MakeNowJust/heredoc/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_MakeNowJust_heredoc_LICENSE
cp vendor/github.com/Microsoft/go-winio/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_Microsoft_go-winio_LICENSE
cp vendor/github.com/Microsoft/hcsshim/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_Microsoft_hcsshim_LICENSE
cp vendor/github.com/NYTimes/gziphandler/LICENSE.md %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_NYTimes_gziphandler_LICENSE.md
cp vendor/github.com/PuerkitoBio/purell/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_PuerkitoBio_purell_LICENSE
cp vendor/github.com/PuerkitoBio/urlesc/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_PuerkitoBio_urlesc_LICENSE
cp vendor/github.com/armon/circbuf/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_armon_circbuf_LICENSE
cp vendor/github.com/asaskevich/govalidator/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_asaskevich_govalidator_LICENSE
cp vendor/github.com/aws/aws-sdk-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_aws_aws-sdk-go_LICENSE.txt
cp vendor/github.com/bazelbuild/bazel-gazelle/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_bazelbuild_bazel-gazelle_LICENSE
cp vendor/github.com/bazelbuild/buildtools/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_bazelbuild_buildtools_LICENSE
cp vendor/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_beorn7_perks_LICENSE
cp vendor/github.com/blang/semver/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_blang_semver_LICENSE
cp vendor/github.com/cespare/prettybench/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_cespare_prettybench_LICENSE.txt
cp vendor/github.com/chai2010/gettext-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_chai2010_gettext-go_LICENSE
cp vendor/github.com/client9/misspell/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_client9_misspell_LICENSE
cp vendor/github.com/cloudflare/cfssl/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_cloudflare_cfssl_LICENSE
cp vendor/github.com/clusterhq/flocker-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_clusterhq_flocker-go_LICENSE
cp vendor/github.com/codedellemc/goscaleio/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_codedellemc_goscaleio_LICENSE
cp vendor/github.com/container-storage-interface/spec/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_container-storage-interface_spec_LICENSE
cp vendor/github.com/containerd/console/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_console_LICENSE
cp vendor/github.com/containerd/containerd/LICENSE.code %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_containerd_LICENSE.code
cp vendor/github.com/containerd/containerd/LICENSE.docs %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_containerd_LICENSE.docs
cp vendor/github.com/containernetworking/cni/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_containernetworking_cni_LICENSE
cp vendor/github.com/coreos/bbolt/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_bbolt_LICENSE
cp vendor/github.com/coreos/etcd/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_etcd_LICENSE
cp vendor/github.com/coreos/go-oidc/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-oidc_LICENSE
cp vendor/github.com/coreos/go-semver/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-semver_LICENSE
cp vendor/github.com/coreos/go-systemd/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-systemd_LICENSE
cp vendor/github.com/coreos/pkg/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_pkg_LICENSE
cp vendor/github.com/cpuguy83/go-md2man/LICENSE.md %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
cp vendor/github.com/cyphar/filepath-securejoin/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_cyphar_filepath-securejoin_LICENSE
cp vendor/github.com/d2g/dhcp4/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_d2g_dhcp4_LICENSE
cp vendor/github.com/d2g/dhcp4client/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_d2g_dhcp4client_LICENSE
cp vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_davecgh_go-spew_LICENSE
cp vendor/github.com/daviddengcn/go-colortext/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_daviddengcn_go-colortext_LICENSE
cp vendor/github.com/dgrijalva/jwt-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_dgrijalva_jwt-go_LICENSE
cp vendor/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_distribution_LICENSE
cp vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_docker_LICENSE
cp vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_docker_NOTICE
cp vendor/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_go-connections_LICENSE
cp vendor/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_go-units_LICENSE
cp vendor/github.com/docker/libnetwork/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_libnetwork_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_spdystream_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE.docs %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_docker_spdystream_LICENSE.docs
cp vendor/github.com/elazarl/goproxy/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_elazarl_goproxy_LICENSE
cp vendor/github.com/emicklei/go-restful/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_emicklei_go-restful_LICENSE
cp vendor/github.com/euank/go-kmsg-parser/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_euank_go-kmsg-parser_LICENSE
cp vendor/github.com/evanphx/json-patch/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_evanphx_json-patch_LICENSE
cp vendor/github.com/exponent-io/jsonpath/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_exponent-io_jsonpath_LICENSE
cp vendor/github.com/fatih/camelcase/LICENSE.md %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_fatih_camelcase_LICENSE.md
cp vendor/github.com/fsnotify/fsnotify/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_fsnotify_fsnotify_LICENSE
cp vendor/github.com/ghodss/yaml/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_ghodss_yaml_LICENSE
cp vendor/github.com/globalsign/mgo/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_LICENSE
cp vendor/github.com/globalsign/mgo/bson/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_bson_LICENSE
cp vendor/github.com/globalsign/mgo/internal/json/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_internal_json_LICENSE
cp vendor/github.com/go-openapi/analysis/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_analysis_LICENSE
cp vendor/github.com/go-openapi/errors/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_errors_LICENSE
cp vendor/github.com/go-openapi/jsonpointer/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_jsonpointer_LICENSE
cp vendor/github.com/go-openapi/jsonreference/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_jsonreference_LICENSE
cp vendor/github.com/go-openapi/loads/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_loads_LICENSE
cp vendor/github.com/go-openapi/runtime/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_runtime_LICENSE
cp vendor/github.com/go-openapi/spec/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_spec_LICENSE
cp vendor/github.com/go-openapi/spec/license.go %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_spec_license.go
cp vendor/github.com/go-openapi/strfmt/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_strfmt_LICENSE
cp vendor/github.com/go-openapi/swag/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_swag_LICENSE
cp vendor/github.com/go-openapi/validate/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_validate_LICENSE
cp vendor/github.com/go-ozzo/ozzo-validation/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_go-ozzo_ozzo-validation_LICENSE
cp vendor/github.com/godbus/dbus/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_godbus_dbus_LICENSE
cp vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_gogo_protobuf_LICENSE
cp vendor/github.com/golang/groupcache/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_golang_groupcache_LICENSE
cp vendor/github.com/golang/mock/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_golang_mock_LICENSE
cp vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_golang_protobuf_LICENSE
cp vendor/github.com/google/btree/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_btree_LICENSE
cp vendor/github.com/google/cadvisor/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_cadvisor_LICENSE
cp vendor/github.com/google/certificate-transparency-go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_certificate-transparency-go_LICENSE
cp vendor/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_go-cmp_LICENSE
cp vendor/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_gofuzz_LICENSE
cp vendor/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_google_uuid_LICENSE
cp vendor/github.com/googleapis/gnostic/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_googleapis_gnostic_LICENSE
cp vendor/github.com/gophercloud/gophercloud/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_gophercloud_gophercloud_LICENSE
cp vendor/github.com/gorilla/websocket/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_gorilla_websocket_LICENSE
cp vendor/github.com/gregjones/httpcache/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_gregjones_httpcache_LICENSE.txt
cp vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_go-grpc-middleware_LICENSE
cp vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_go-grpc-prometheus_LICENSE
cp vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_grpc-gateway_LICENSE.txt
cp vendor/github.com/hashicorp/golang-lru/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_hashicorp_golang-lru_LICENSE
cp vendor/github.com/hashicorp/hcl/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_hashicorp_hcl_LICENSE
cp vendor/github.com/heketi/heketi/COPYING-GPLV2 %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_COPYING-GPLV2
cp vendor/github.com/heketi/heketi/COPYING-LGPLV3 %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_COPYING-LGPLV3
cp vendor/github.com/heketi/heketi/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_LICENSE
cp vendor/github.com/heketi/heketi/LICENSE-APACHE2 %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_LICENSE-APACHE2
cp vendor/github.com/hpcloud/tail/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_hpcloud_tail_LICENSE.txt
cp vendor/github.com/hpcloud/tail/ratelimiter/Licence %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_hpcloud_tail_ratelimiter_Licence
cp vendor/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_imdario_mergo_LICENSE
cp vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_inconshreveable_mousetrap_LICENSE
cp vendor/github.com/jmespath/go-jmespath/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_jmespath_go-jmespath_LICENSE
cp vendor/github.com/jonboulle/clockwork/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_jonboulle_clockwork_LICENSE
cp vendor/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_json-iterator_go_LICENSE
cp vendor/github.com/jstemmer/go-junit-report/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_jstemmer_go-junit-report_LICENSE
cp vendor/github.com/jteeuwen/go-bindata/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_jteeuwen_go-bindata_LICENSE
cp vendor/github.com/kardianos/osext/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_kardianos_osext_LICENSE
cp vendor/github.com/karrick/godirwalk/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_karrick_godirwalk_LICENSE
cp vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
cp vendor/github.com/kr/fs/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_kr_fs_LICENSE
cp vendor/github.com/libopenstorage/openstorage/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_libopenstorage_openstorage_LICENSE
cp vendor/github.com/liggitt/tabwriter/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_liggitt_tabwriter_LICENSE
cp vendor/github.com/lithammer/dedent/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_lithammer_dedent_LICENSE
cp vendor/github.com/magiconair/properties/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_magiconair_properties_LICENSE
cp vendor/github.com/mailru/easyjson/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mailru_easyjson_LICENSE
cp vendor/github.com/marstr/guid/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_marstr_guid_LICENSE.txt
cp vendor/github.com/mattn/go-shellwords/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mattn_go-shellwords_LICENSE
cp vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
cp vendor/github.com/mholt/caddy/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mholt_caddy_LICENSE.txt
cp vendor/github.com/miekg/dns/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_miekg_dns_LICENSE
cp vendor/github.com/mindprince/gonvml/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mindprince_gonvml_LICENSE
cp vendor/github.com/mistifyio/go-zfs/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mistifyio_go-zfs_LICENSE
cp vendor/github.com/mitchellh/go-wordwrap/LICENSE.md %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mitchellh_go-wordwrap_LICENSE.md
cp vendor/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mitchellh_mapstructure_LICENSE
cp vendor/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_modern-go_concurrent_LICENSE
cp vendor/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_modern-go_reflect2_LICENSE
cp vendor/github.com/mohae/deepcopy/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mohae_deepcopy_LICENSE
cp vendor/github.com/morikuni/aec/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_morikuni_aec_LICENSE
cp vendor/github.com/mrunalp/fileutils/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mrunalp_fileutils_LICENSE
cp vendor/github.com/mvdan/xurls/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mvdan_xurls_LICENSE
cp vendor/github.com/mxk/go-flowrate/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_mxk_go-flowrate_LICENSE
cp vendor/github.com/onsi/ginkgo/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
cp vendor/github.com/onsi/gomega/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_gomega_LICENSE
cp vendor/github.com/opencontainers/go-digest/LICENSE.code %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_go-digest_LICENSE.code
cp vendor/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_go-digest_LICENSE.docs
cp vendor/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_image-spec_LICENSE
cp vendor/github.com/opencontainers/runc/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_runc_LICENSE
cp vendor/github.com/opencontainers/runtime-spec/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_runtime-spec_LICENSE
cp vendor/github.com/opencontainers/selinux/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_selinux_LICENSE
cp vendor/github.com/pborman/uuid/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pborman_uuid_LICENSE
cp vendor/github.com/pelletier/go-toml/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pelletier_go-toml_LICENSE
cp vendor/github.com/peterbourgon/diskv/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_peterbourgon_diskv_LICENSE
cp vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pkg_errors_LICENSE
cp vendor/github.com/pkg/sftp/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pkg_sftp_LICENSE
cp vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pmezard_go-difflib_LICENSE
cp vendor/github.com/pquerna/cachecontrol/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_pquerna_cachecontrol_LICENSE
cp vendor/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_golang_LICENSE
cp vendor/github.com/prometheus/client_golang/NOTICE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_golang_NOTICE
cp vendor/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_model_LICENSE
cp vendor/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_common_LICENSE
cp vendor/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_procfs_LICENSE
cp vendor/github.com/quobyte/api/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_quobyte_api_LICENSE
cp vendor/github.com/robfig/cron/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_robfig_cron_LICENSE
cp vendor/github.com/rubiojr/go-vhd/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_rubiojr_go-vhd_LICENSE
cp vendor/github.com/russross/blackfriday/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_russross_blackfriday_LICENSE.txt
cp vendor/github.com/satori/go.uuid/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_satori_go.uuid_LICENSE
cp vendor/github.com/seccomp/libseccomp-golang/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_seccomp_libseccomp-golang_LICENSE
cp vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_shurcooL_sanitized_anchor_name_LICENSE
cp vendor/github.com/sigma/go-inotify/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_sigma_go-inotify_LICENSE
cp vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_sirupsen_logrus_LICENSE
cp vendor/github.com/soheilhy/cmux/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_soheilhy_cmux_LICENSE
cp vendor/github.com/spf13/afero/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_afero_LICENSE.txt
cp vendor/github.com/spf13/cast/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_cast_LICENSE
cp vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_cobra_LICENSE.txt
cp vendor/github.com/spf13/jwalterweatherman/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_jwalterweatherman_LICENSE
cp vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_pflag_LICENSE
cp vendor/github.com/spf13/viper/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_viper_LICENSE
cp vendor/github.com/storageos/go-api/LICENCE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_storageos_go-api_LICENCE
cp vendor/github.com/stretchr/objx/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_stretchr_objx_LICENSE
cp vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_stretchr_testify_LICENSE
cp vendor/github.com/syndtr/gocapability/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_syndtr_gocapability_LICENSE
cp vendor/github.com/tmc/grpc-websocket-proxy/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_tmc_grpc-websocket-proxy_LICENSE
cp vendor/github.com/vishvananda/netlink/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vishvananda_netlink_LICENSE
cp vendor/github.com/vishvananda/netns/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vishvananda_netns_LICENSE
cp vendor/github.com/vmware/govmomi/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_LICENSE.txt
cp vendor/github.com/vmware/govmomi/simulator/license_manager.go %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_simulator_license_manager.go
cp vendor/github.com/vmware/govmomi/vim25/xml/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_vim25_xml_LICENSE
cp vendor/github.com/vmware/photon-controller-go-sdk/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_photon-controller-go-sdk_LICENSE
cp vendor/github.com/vmware/photon-controller-go-sdk/SSPI/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_photon-controller-go-sdk_SSPI_LICENSE.txt
cp vendor/github.com/xanzy/go-cloudstack/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_xanzy_go-cloudstack_LICENSE
cp vendor/github.com/xanzy/go-cloudstack/cloudstack/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_xanzy_go-cloudstack_cloudstack_LICENSE
cp vendor/github.com/xiang90/probing/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_github.com_xiang90_probing_LICENSE
cp vendor/go.uber.org/atomic/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_go.uber.org_atomic_LICENSE.txt
cp vendor/go.uber.org/multierr/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_go.uber.org_multierr_LICENSE.txt
cp vendor/go.uber.org/zap/LICENSE.txt %{buildroot}/usr/share/package-licenses/kubernetes/vendor_go.uber.org_zap_LICENSE.txt
cp vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_crypto_LICENSE
cp vendor/golang.org/x/lint/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_lint_LICENSE
cp vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_net_LICENSE
cp vendor/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_oauth2_LICENSE
cp vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_sys_LICENSE
cp vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_text_LICENSE
cp vendor/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_time_LICENSE
cp vendor/golang.org/x/tools/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_golang.org_x_tools_LICENSE
cp vendor/gonum.org/v1/gonum/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gonum.org_v1_gonum_LICENSE
cp vendor/google.golang.org/api/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_google.golang.org_api_LICENSE
cp vendor/google.golang.org/api/googleapi/internal/uritemplates/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_google.golang.org_api_googleapi_internal_uritemplates_LICENSE
cp vendor/google.golang.org/appengine/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_google.golang.org_appengine_LICENSE
cp vendor/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_google.golang.org_genproto_LICENSE
cp vendor/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_google.golang.org_grpc_LICENSE
cp vendor/gopkg.in/fsnotify.v1/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_fsnotify.v1_LICENSE
cp vendor/gopkg.in/gcfg.v1/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_gcfg.v1_LICENSE
cp vendor/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_inf.v0_LICENSE
cp vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_natefinch_lumberjack.v2_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_square_go-jose.v2_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/json/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
cp vendor/gopkg.in/tomb.v1/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_tomb.v1_LICENSE
cp vendor/gopkg.in/warnings.v0/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_warnings.v0_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
cp vendor/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_NOTICE
cp vendor/k8s.io/gengo/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_gengo_LICENSE
cp vendor/k8s.io/heapster/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_heapster_LICENSE
cp vendor/k8s.io/klog/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_klog_LICENSE
cp vendor/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_kube-openapi_LICENSE
cp vendor/k8s.io/repo-infra/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_repo-infra_LICENSE
cp vendor/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_k8s.io_utils_LICENSE
cp vendor/sigs.k8s.io/kustomize/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_kustomize_LICENSE
cp vendor/sigs.k8s.io/structured-merge-diff/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_structured-merge-diff_LICENSE
cp vendor/sigs.k8s.io/yaml/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_yaml_LICENSE
cp vendor/vbom.ml/util/LICENSE %{buildroot}/usr/share/package-licenses/kubernetes/vendor_vbom.ml_util_LICENSE
output_path="_output/bin/"
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/kube-apiserver.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/kube-controller-manager.service
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/kube-proxy.service
install -m 0644 %{SOURCE4} %{buildroot}/usr/lib/systemd/system/kube-scheduler.service
install -m 0644 %{SOURCE5} %{buildroot}/usr/lib/systemd/system/kubelet-motd.service
install -m 0644 %{SOURCE6} %{buildroot}/usr/lib/systemd/system/kubelet.service
## install_append content
install -m 755 -d %{buildroot}%{_bindir}
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kubeadm
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kubectl
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kubelet
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kube-proxy
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kube-controller-manager
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kube-scheduler
install -p -m 755 -t %{buildroot}%{_bindir} ${output_path}/kube-apiserver
mkdir -p %{buildroot}/usr/bin
install -m0755 kubelet-version-check.sh %{buildroot}/usr/bin/kubelet-version-check.sh
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -sf ../kubelet-motd.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/kubelet-motd.service
mkdir -p %{buildroot}/usr/lib/systemd/network/
install -m0644 70-vxlan.link %{buildroot}/usr/lib/systemd/network/70-vxlan.link
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/systemd/network/70-vxlan.link

%files bin
%defattr(-,root,root,-)
/usr/bin/kubeadm
/usr/bin/kubectl
/usr/bin/kubelet
/usr/bin/kubelet-version-check.sh

%files extras
%defattr(-,root,root,-)
/usr/bin/kube-apiserver
/usr/bin/kube-controller-manager
/usr/bin/kube-proxy
/usr/bin/kube-scheduler

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kubernetes/Godeps_LICENSES
/usr/share/package-licenses/kubernetes/LICENSE
/usr/share/package-licenses/kubernetes/logo_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_api_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apiextensions-apiserver_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apimachinery_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_apiserver_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cli-runtime_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_client-go_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cloud-provider_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cluster-bootstrap_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_code-generator_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_component-base_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_cri-api_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_csi-translation-lib_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-aggregator_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-controller-manager_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-proxy_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kube-scheduler_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kubectl_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_kubelet_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_legacy-cloud-providers_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_metrics_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_node-api_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-apiserver_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-cli-plugin_LICENSE
/usr/share/package-licenses/kubernetes/staging_src_k8s.io_sample-controller_LICENSE
/usr/share/package-licenses/kubernetes/third_party_forked_golang_LICENSE
/usr/share/package-licenses/kubernetes/third_party_forked_gonum_graph_LICENSE
/usr/share/package-licenses/kubernetes/third_party_forked_shell2junit_LICENSE
/usr/share/package-licenses/kubernetes/third_party_go-srcimporter_LICENSE
/usr/share/package-licenses/kubernetes/third_party_intemp_LICENSE
/usr/share/package-licenses/kubernetes/third_party_multiarch_qemu-user-static_LICENSE
/usr/share/package-licenses/kubernetes/vendor_bitbucket.org_bertimus9_systemstat_LICENSE
/usr/share/package-licenses/kubernetes/vendor_cloud.google.com_go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_azure-sdk-for-go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_go-ansiterm_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_Azure_go-autorest_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_GoogleCloudPlatform_k8s-cloud-provider_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_JeffAshton_win_pdh_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_MakeNowJust_heredoc_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_Microsoft_go-winio_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_Microsoft_hcsshim_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_NYTimes_gziphandler_LICENSE.md
/usr/share/package-licenses/kubernetes/vendor_github.com_PuerkitoBio_purell_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_PuerkitoBio_urlesc_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_armon_circbuf_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_asaskevich_govalidator_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_aws_aws-sdk-go_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_bazelbuild_bazel-gazelle_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_bazelbuild_buildtools_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_beorn7_perks_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_blang_semver_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_cespare_prettybench_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_chai2010_gettext-go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_client9_misspell_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_cloudflare_cfssl_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_clusterhq_flocker-go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_codedellemc_goscaleio_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_container-storage-interface_spec_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_console_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_containerd_LICENSE.code
/usr/share/package-licenses/kubernetes/vendor_github.com_containerd_containerd_LICENSE.docs
/usr/share/package-licenses/kubernetes/vendor_github.com_containernetworking_cni_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_bbolt_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_etcd_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-oidc_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-semver_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_go-systemd_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_coreos_pkg_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
/usr/share/package-licenses/kubernetes/vendor_github.com_cyphar_filepath-securejoin_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_d2g_dhcp4_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_d2g_dhcp4client_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_davecgh_go-spew_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_daviddengcn_go-colortext_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_dgrijalva_jwt-go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_distribution_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_docker_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_docker_NOTICE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_go-connections_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_go-units_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_libnetwork_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_spdystream_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_docker_spdystream_LICENSE.docs
/usr/share/package-licenses/kubernetes/vendor_github.com_elazarl_goproxy_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_emicklei_go-restful_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_euank_go-kmsg-parser_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_evanphx_json-patch_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_exponent-io_jsonpath_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_fatih_camelcase_LICENSE.md
/usr/share/package-licenses/kubernetes/vendor_github.com_fsnotify_fsnotify_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_ghodss_yaml_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_bson_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_globalsign_mgo_internal_json_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_analysis_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_errors_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_jsonpointer_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_jsonreference_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_loads_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_runtime_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_spec_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_spec_license.go
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_strfmt_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_swag_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-openapi_validate_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_go-ozzo_ozzo-validation_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_godbus_dbus_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_gogo_protobuf_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_golang_groupcache_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_golang_mock_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_golang_protobuf_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_btree_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_cadvisor_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_certificate-transparency-go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_go-cmp_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_gofuzz_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_google_uuid_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_googleapis_gnostic_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_gophercloud_gophercloud_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_gorilla_websocket_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_gregjones_httpcache_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_go-grpc-middleware_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_go-grpc-prometheus_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_grpc-ecosystem_grpc-gateway_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_hashicorp_golang-lru_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_hashicorp_hcl_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_COPYING-GPLV2
/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_COPYING-LGPLV3
/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_heketi_heketi_LICENSE-APACHE2
/usr/share/package-licenses/kubernetes/vendor_github.com_hpcloud_tail_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_hpcloud_tail_ratelimiter_Licence
/usr/share/package-licenses/kubernetes/vendor_github.com_imdario_mergo_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_inconshreveable_mousetrap_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_jmespath_go-jmespath_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_jonboulle_clockwork_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_json-iterator_go_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_jstemmer_go-junit-report_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_jteeuwen_go-bindata_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_kardianos_osext_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_karrick_godirwalk_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_kr_fs_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_libopenstorage_openstorage_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_liggitt_tabwriter_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_lithammer_dedent_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_magiconair_properties_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mailru_easyjson_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_marstr_guid_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_mattn_go-shellwords_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mholt_caddy_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_miekg_dns_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mindprince_gonvml_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mistifyio_go-zfs_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mitchellh_go-wordwrap_LICENSE.md
/usr/share/package-licenses/kubernetes/vendor_github.com_mitchellh_mapstructure_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_modern-go_concurrent_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_modern-go_reflect2_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mohae_deepcopy_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_morikuni_aec_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mrunalp_fileutils_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mvdan_xurls_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_mxk_go-flowrate_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_onsi_gomega_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_go-digest_LICENSE.code
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_go-digest_LICENSE.docs
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_image-spec_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_runc_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_runtime-spec_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_opencontainers_selinux_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pborman_uuid_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pelletier_go-toml_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_peterbourgon_diskv_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pkg_errors_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pkg_sftp_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pmezard_go-difflib_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_pquerna_cachecontrol_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_golang_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_golang_NOTICE
/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_client_model_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_common_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_prometheus_procfs_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_quobyte_api_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_robfig_cron_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_rubiojr_go-vhd_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_russross_blackfriday_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_satori_go.uuid_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_seccomp_libseccomp-golang_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_shurcooL_sanitized_anchor_name_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_sigma_go-inotify_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_sirupsen_logrus_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_soheilhy_cmux_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_afero_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_cast_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_cobra_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_jwalterweatherman_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_pflag_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_spf13_viper_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_storageos_go-api_LICENCE
/usr/share/package-licenses/kubernetes/vendor_github.com_stretchr_objx_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_stretchr_testify_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_syndtr_gocapability_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_tmc_grpc-websocket-proxy_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_vishvananda_netlink_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_vishvananda_netns_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_simulator_license_manager.go
/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_govmomi_vim25_xml_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_photon-controller-go-sdk_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_vmware_photon-controller-go-sdk_SSPI_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_github.com_xanzy_go-cloudstack_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_xanzy_go-cloudstack_cloudstack_LICENSE
/usr/share/package-licenses/kubernetes/vendor_github.com_xiang90_probing_LICENSE
/usr/share/package-licenses/kubernetes/vendor_go.uber.org_atomic_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_go.uber.org_multierr_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_go.uber.org_zap_LICENSE.txt
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_crypto_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_lint_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_net_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_oauth2_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_sys_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_text_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_time_LICENSE
/usr/share/package-licenses/kubernetes/vendor_golang.org_x_tools_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gonum.org_v1_gonum_LICENSE
/usr/share/package-licenses/kubernetes/vendor_google.golang.org_api_LICENSE
/usr/share/package-licenses/kubernetes/vendor_google.golang.org_api_googleapi_internal_uritemplates_LICENSE
/usr/share/package-licenses/kubernetes/vendor_google.golang.org_appengine_LICENSE
/usr/share/package-licenses/kubernetes/vendor_google.golang.org_genproto_LICENSE
/usr/share/package-licenses/kubernetes/vendor_google.golang.org_grpc_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_fsnotify.v1_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_gcfg.v1_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_inf.v0_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_natefinch_lumberjack.v2_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_square_go-jose.v2_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_tomb.v1_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_warnings.v0_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_LICENSE
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
/usr/share/package-licenses/kubernetes/vendor_gopkg.in_yaml.v2_NOTICE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_gengo_LICENSE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_heapster_LICENSE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_klog_LICENSE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_kube-openapi_LICENSE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_repo-infra_LICENSE
/usr/share/package-licenses/kubernetes/vendor_k8s.io_utils_LICENSE
/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_kustomize_LICENSE
/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_structured-merge-diff_LICENSE
/usr/share/package-licenses/kubernetes/vendor_sigs.k8s.io_yaml_LICENSE
/usr/share/package-licenses/kubernetes/vendor_vbom.ml_util_LICENSE

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/kube-apiserver.service
/usr/lib/systemd/system/kube-controller-manager.service
/usr/lib/systemd/system/kube-proxy.service
/usr/lib/systemd/system/kube-scheduler.service
/usr/lib/systemd/system/kubelet-motd.service
/usr/lib/systemd/system/kubelet.service
/usr/lib/systemd/system/update-triggers.target.wants/kubelet-motd.service
