#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kubernetes
Version  : 1.0.4
Release  : 5
URL      : https://github.com/kubernetes/kubernetes/archive/v1.0.4.tar.gz
Source0  : https://github.com/kubernetes/kubernetes/archive/v1.0.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-3.0 LGPL-3.0 MIT
BuildRequires : go
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : rsync
BuildRequires : setuptools
Patch1: 0001-assetsize-fix.patch
Patch2: 0002-makeinstall.patch

%description
### Local development
1) Install Go
2) Install Redis
Now start a local redis instance

%prep
%setup -q -n kubernetes-1.0.4
%patch1 -p1
%patch2 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
